Simple auto increment logic for item number
mmmnmnm/lahmacun_arcsi pull request #29
Opened 2020-10-31 12:27 UTC by gammaw

#14

See more details in the issue. https://github.com/mmmnmnm/lahmacun_arcsi/issues/14

2020-11-09 01:33 UTC, pvj requested changes
Thanks for this, it's good code! I am still bit unsure if this is the right place for this indeed needed functionality and would advocate for something else. But since it is small change I think we could start w/ it living here and continue discussions further. But even, before we merge it I would suggest we use queries.

2020-11-09 01:33 UTC, pvj commented on arcsi/api/item.py
> +        show_request = requests.get(app.config["APP_BASE_URL"] + url_for("arcsi.view_show", id=show_id))
I've read your comment in issue #14 and while it is true it doesn't have perf indication with our current usage we will definitely have to write this over so why not try it right first? This feels bit unnecessary. In my opinion, we have the `Show` object available to instantiate and could query & filter that which returns only the latest episode only if it has one, all in one.

2020-11-09 01:33 UTC, pvj commented on arcsi/api/item.py
> +            items_sorted = sorted(show_dict["items"], key=lambda k: k['number'], reverse = True)
👍

2020-11-09 01:33 UTC, pvj commented on arcsi/templates/item/add.html
> +    <label for="number">Episode number (+1 by def)</label>
I would try to word this differently. Leave empty to auto-increment or some such.

2020-11-19 18:41 UTC, gammaw commented
I'm closing this, see details in https://github.com/mmmnmnm/lahmacun_arcsi/issues/14

2020-11-19 18:41 UTC, closed without merging